In [1]:
import numpy as np

In [21]:
myVect = np.array([1, 2, 3, 4])

In [22]:
myVect

array([1, 2, 3, 4])

In [4]:
myVect2 = np.arange(1, 10, 2)

In [5]:
myVect2

array([1, 3, 5, 7, 9])

In [8]:
myVect3 = np.array(np.int16([1, 2, 3, 4]))

In [11]:
myVect3

array([1, 2, 3, 4], dtype=int16)

In [12]:
myVect

array([1, 2, 3, 4])

In [13]:
myVect = np.ones(4)

In [14]:
myVect

array([1., 1., 1., 1.])

In [15]:
myVect4 = np.ones(4, np.int16)

In [16]:
myVect4

array([1, 1, 1, 1], dtype=int16)

In [17]:
myZeroVect = np.zeros(10, np.int16)

In [18]:
myZeroVect

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [19]:
myVect5 = myVect4 + 2

In [20]:
myVect5

array([3, 3, 3, 3], dtype=int16)

In [23]:
myvect6 = myVect + 10

In [24]:
myvect6

array([11, 12, 13, 14])

In [25]:
myvect7 = 2 ** myVect5

In [42]:
myvect7 = np.array(np.int32(myvect7))

In [44]:
myvect7.dtype

dtype('int32')

In [45]:
myvect8 = 4 ** myvect7

In [46]:
myvect8a

array([65536, 65536, 65536, 65536], dtype=int32)

In [48]:
a = np.array([1, 2, 3, 4])

In [49]:
b = np.array([2, 2, 4, 4])

In [50]:
a == b

array([False,  True, False,  True])

In [51]:
a < b

array([ True, False,  True, False])

In [52]:
a > b

array([False, False, False, False])

In [53]:
a = np.array([True, False, True, False])

In [54]:
b = np.array([True, True, False, False])

In [55]:
np.logical_or(a, b)

array([ True,  True,  True, False])

In [56]:
np.logical_and(a, b)

array([ True, False, False, False])

In [57]:
np.logical_not(a, b)

array([False,  True, False,  True])

In [58]:
np.logical_xor(a, b)

array([ True,  True,  True,  True])

In [59]:
myvect8 = myVect * myVect

In [60]:
myvect8

array([ 1,  4,  9, 16])

In [61]:
myvect9 = np.multiply(myVect, myVect)

In [63]:
myvect9

array([ 1,  4,  9, 16])

In [64]:
myvect8 == myvect9

array([ True,  True,  True,  True])

In [69]:
myvect9.dot(myvect9)

354

In [70]:
2+2

4

In [72]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [73]:
matrix1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
matrix1[2,1]

8

In [77]:
matrix1[1,2]

6

In [78]:
matrix2 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [79]:
matrix2

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [80]:
matrix2[0, 1, 1]

4

In [83]:
matrix2[1, 0, 1]

6

In [85]:
matrix3 = np.ones([4, 5], dtype=np.int16)

In [86]:
matrix3

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

In [87]:
matrix4 = np.ones([4, 4, 4], dtype=np.bool)

In [88]:
matrix4

array([[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],

       [[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]]])

In [89]:
matrix5 = np.mat([[1, 2, 3], [4, 5, 6]])

In [90]:
matrix5

matrix([[1, 2, 3],
        [4, 5, 6]])

In [91]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [92]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [93]:
a * b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [94]:
c = np.matrix([[1, 2, 3], [4, 5, 6]])

In [97]:
d = np.matrix([[1, 2, 3], [4, 5, 6], [7,8,9]])

In [99]:
c.dot(d)

matrix([[30, 36, 42],
        [66, 81, 96]])

In [103]:
c * d

matrix([[30, 36, 42],
        [66, 81, 96]])

In [106]:
changeit = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
changeit.reshape(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [115]:
changeit2 = changeit.reshape(2, 2, 2, 1)

In [118]:
type(changeit)

numpy.ndarray

In [120]:
type(changeit2)

numpy.ndarray

In [121]:
np.transpose(changeit)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [122]:
np.transpose(c)

matrix([[1, 4],
        [2, 5],
        [3, 6]])

In [123]:
np.transpose(changeit2)

array([[[[1, 5],
         [3, 7]],

        [[2, 6],
         [4, 8]]]])

In [125]:
changeit2

array([[[[1],
         [2]],

        [[3],
         [4]]],


       [[[5],
         [6]],

        [[7],
         [8]]]])

In [126]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [127]:
e = np.array([[1, 2], [3, 4]])

In [128]:
e

array([[1, 2],
       [3, 4]])

In [130]:
f = np.linalg.inv(e)

In [131]:
f

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [134]:
np.allclose(np.dot(e, f), np.identity(2))

True

In [135]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [139]:
np.random.permutation(a)

array([[4, 5, 6],
       [1, 2, 3]])

In [160]:
k = np.array([1, 2, 3, 4])

In [161]:
np.random.permutation(k)

array([4, 2, 3, 1])

In [142]:
from itertools import permutations

In [162]:
k

array([1, 2, 3, 4])

In [163]:
for p in permutations(k):
    print(p)

(1, 2, 3, 4)
(1, 2, 4, 3)
(1, 3, 2, 4)
(1, 3, 4, 2)
(1, 4, 2, 3)
(1, 4, 3, 2)
(2, 1, 3, 4)
(2, 1, 4, 3)
(2, 3, 1, 4)
(2, 3, 4, 1)
(2, 4, 1, 3)
(2, 4, 3, 1)
(3, 1, 2, 4)
(3, 1, 4, 2)
(3, 2, 1, 4)
(3, 2, 4, 1)
(3, 4, 1, 2)
(3, 4, 2, 1)
(4, 1, 2, 3)
(4, 1, 3, 2)
(4, 2, 1, 3)
(4, 2, 3, 1)
(4, 3, 1, 2)
(4, 3, 2, 1)


In [164]:
from itertools import combinations

In [165]:
a = np.array([1, 2, 3, 4])

In [166]:
for comb in combinations(a, 2):
    print(comb)

(1, 2)
(1, 3)
(1, 4)
(2, 3)
(2, 4)
(3, 4)


In [167]:
pool = []

In [169]:
for comb in combinations(a, 2):
    pool.append(comb)

In [170]:
pool

[(1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)]

In [175]:
import random

In [188]:
random.sample(pool, 3)

[(2, 4), (3, 4), (1, 2)]

In [194]:
ab = [1, 2, 3, 4, 5]

In [196]:
random.shuffle(ab)

In [197]:
ab

[5, 3, 4, 2, 1]

In [198]:
aa = np.array([1, 2, 2, 2, 3, 4, 5, 5, 6, 6, 7, 7, 7, 7, 8, 8, 9])

In [199]:
bb = np.array(set(list(aa)))

In [200]:
bb

array({1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

In [2]:
def factorial(n):
    if n == 1 or n == 0:
        return 1
    else:
        return n * factorial(n - 1)
print(factorial(5))

120


In [1]:
1+2

3

In [3]:
def factorial(n):
    result = 1
    while n > 1:
        result = result * n
        n = n - 1
    return result
        
print(factorial(10))

3628800


In [2]:
aList = list(range(1, 399))

In [7]:
def search(searchlist, key):
    print('Общее количество элементов в списке = ', len(searchlist), '\n')
    mid = int(len(searchlist)) // 2
    print('Средняя точка = ', str(mid))
    
    if mid == 0:
        print('Key not found.')
        return key
    elif key == searchlist[mid]:
        print('KEY FOUND! It is', searchlist[mid])
        return searchlist[mid]
    elif key > searchlist[mid]:
        print('Now the searchlist contains ',
             searchlist[mid:len(searchlist)], '\n')
        search(searchlist[mid:len(searchlist)], key)
        
    else:
        print('Now searchlist contains ', searchlist[:mid], '\n')
        search(searchlist[:mid], key)
        
search(aList, 500)

Общее количество элементов в списке =  398 

Средняя точка =  199
Now the searchlist contains  [200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380,